@extends('admin.admin_master')
@section('admin')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <h4 class="card-title">Change Password Page </h4> <br> <br>


                        @if (count($errors))
                        @foreach ( $errors->all() as $error )
                            <p class="alert alert-danger">{{$error}}</p>
                        @endforeach

                        @endif
                        <form  method="POST" action="{{route('update.password')}}" >
                            @csrf    <!--A CSRF token is a unique, secret, and unpredictable value that is generated by the server-side application and shared with the client. When issuing a request to perform a sensitive action, such as submitting a form, the client must include the correct CSRF token-->

                            <div class="row mb-3">
                                <label for="example-text-input" class="col-sm-2 col-form-label">Old Password</label>
                                <div class="col-sm-10">
                                    <input name="oldpassword" class="form-control" type="password" value="" id="oldpassword">
                                </div>
                            </div>
                            <!-- end row -->
                            <div class="row mb-3">
                                <label for="example-text-input" class="col-sm-2 col-form-label">New Password</label>
                                <div class="col-sm-10">
                                    <input name="newpassword" class="form-control" type="password" value="" id="newpassword">
                                </div>
                            </div>
                            <!-- end row -->
                            <div class="row mb-3">
                                <label for="example-text-input" class="col-sm-2 col-form-label">Confirm Password</label>
                                <div class="col-sm-10">
                                    <input name="confirm_password" class="form-control" type="password" value="" id="confirm_password">
                                </div>
                            </div>
                            <!-- end row -->


                        <input class="btn btn-primary" value="Change Password" type="submit">
                    </form>
                        <!-- end row -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
