@extends('admin.admin_master')
@section('admin')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">

                        <h4 class="card-title">Edit Multi Image </h4>
                        <form  method="POST" action="{{route('Update.multi.image')}}" enctype="multipart/form-data">
                            @csrf    <!--A CSRF token is a unique, secret, and unpredictable value that is generated by the server-side application and shared with the client. When issuing a request to perform a sensitive action, such as submitting a form, the client must include the correct CSRF token-->


                            <input type="hidden" name="id" value="{{$multiimage->id}}">  <!-- Here we get the id value as hidden-->
                            <div class="row mb-3">
                                <label for="example-text-input" class="col-sm-2 col-form-label">Edit Multi Image</label>
                                <div class="col-sm-10">
                                    <input name="multi_images"  class="form-control" type="file" value="" id="image">
                                </div>
                            </div>

                            <div class="row mb-3">
                                <label for="example-text-input" class="col-sm-2 col-form-label"> </label>
                                <div class="col-sm-10">
                                    <img src="{{asset($multiimage->multi_images)}}" class="rounded avatar-lg" id="showimage" alt="">  <!--In this we can access the database using the variable $editdata so we have to use it here.Here we not use url('upload/home_slide/'.$homeslide->home_slide) because we already saved the image with url so no need of it.-->
                                </div>
                            </div>
                        <input class="btn btn-primary" value="Update About Page" type="submit">
                    </form>
                        <!-- end row -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function(){
        $('#image').change(function(e){
            var reader = new FileReader();
            reader.onload = function(e){
                $('#showimage').attr('src',e.target.result);
            }
            reader.readAsDataURL(e.target.files['0']);
        });
    });
</script>
@endsection
